import { useEffect, useRef, useState } from 'react';
import { AnimatePresence, motion, useReducedMotion } from 'framer-motion';
import { ArrowUpRight, Check, ChevronRight, Circle, Flag, Headphones, MessageCircle, Mic, MicOff, Plus, Send, ShieldCheck, Sparkles, Users, Video, Volume2, VolumeX, X, Zap } from 'lucide-react';
import { Link, useNavigate, useParams } from 'react-router-dom';
import { Avatar, Button, Card, LevelBadge, Modal, OnDeviceBadge, OrbitArt, ProgressRing, SectionHeading, Shell } from '../components';
import { AppState, useApp } from '../store/useApp';
import { Box, User } from '../types';
import { mockAI } from '../ai/mockAI';

export function StudioRoom() {
  const { boxId = '214' } = useParams(); const app = useApp(); const nav = useNavigate();
  const box = app.boxes.find(b => b.id === boxId);
  const [tab, setTab] = useState('Crew'); const [profile, setProfile] = useState<User | null>(null);
  const tabs = [{ title: 'Crew', Icon: Users }, { title: 'Chat', Icon: MessageCircle }, { title: 'Sprint', Icon: Flag }, { title: 'Calls', Icon: Headphones }];
  if (!box) return <Shell title="Crew room"><div className="empty-state"><h3>This orbit isn't on the map.</h3><Link to="/explore" className="btn btn-primary">Explore boxes</Link></div></Shell>;
  return <Shell title={box.name}><div className="room-title-row"><div><span className="eyebrow">A SHARED KIND OF SERIOUS / {box.type}</span><h1>{box.name}<span>.</span></h1><div className="room-subtitle"><LevelBadge level={box.level} /><span>Day {box.sprintDay} of 14</span><span className="room-live"><i />{box.status === 'Open' ? 'Assembling crew' : 'In motion'}</span></div></div><div className="room-health"><ProgressRing value={box.health} size={85} /><span>TEAM MOMENTUM</span></div></div><div className="studio-tabs" role="tablist" aria-label="Crew room sections">{tabs.map(({ title, Icon }, i) => <button key={title} id={`tab-${title}`} role="tab" aria-controls={`panel-${title}`} aria-selected={tab === title} tabIndex={tab === title ? 0 : -1} onClick={() => setTab(title)} onKeyDown={e => { if (e.key === 'ArrowRight' || e.key === 'ArrowLeft') { const next = tabs[(i + (e.key === 'ArrowRight' ? 1 : 3)) % 4].title; setTab(next); document.getElementById(`tab-${next}`)?.focus(); } }} className={tab === title ? 'active' : ''}><Icon size={16} />{title}<small>0{i + 1}</small></button>)}<span className="room-tab-note"><ShieldCheck size={12} />A little space to build together.</span></div>
    <div id={`panel-${tab}`} role="tabpanel" aria-labelledby={`tab-${tab}`}>{tab === 'Crew' && <><div className="crew-manifest"><div><span className="eyebrow">MEET THE PEOPLE BEHIND THE POSSIBILITY</span><h2>Different strengths.<br /><span>One shared direction.</span></h2><p>Great teams aren't five of the same person.<br />They're five reasons to believe it can work.</p></div><OrbitArt variant="lavender" /></div><div className="crew-passports">{box.slots.map((slot, i) => { const u = app.users.find(u => u.id === slot.filledBy); return u ? <button className="crew-passport" key={i} onClick={() => setProfile(u)}><div className="passport-top"><span>CREW / 0{i + 1}</span><ArrowUpRight size={18} /></div><Avatar user={u} size="lg" /><div className="passport-name"><h3>{u.name}</h3>{u.id === app.currentUser?.id && <span>YOU</span>}</div><span className="passport-role">{u.role}</span><p>{u.bio}</p><div className="tag-row">{u.skills.slice(0, 3).map(s => <span key={s}>{s}</span>)}</div><div className="passport-bottom"><span><i />{u.hoursPerWeek} hrs / week</span><span>{u.reputation} reputation</span></div></button> : <button key={i} className="crew-passport open-passport" onClick={() => app.setToast('Invite link copied for this local demo.')}><span className="eyebrow">ONE MORE PERSPECTIVE</span><div className="open-seat"><Plus size={30} /></div><h3>A seat for<br />a {slot.role.toLowerCase()}.</h3><p>The next great teammate<br />might be one hello away.</p><span className="open-seat-link">Invite someone <ArrowUpRight size={16} /></span></button>; })}</div><div className="demo-day-banner"><div><Flag size={23} /><span><b>A small sprint. A real signal.</b><small>Ship a demo, share feedback, and decide what comes next.</small></span></div><Button variant="ghost" onClick={() => { app.fastForward(box.id); nav(`/sprint/${box.id}/end`); }}>Fast-forward to Day 14 <ArrowUpRight size={16} /></Button></div></>}{tab === 'Chat' && <StudioChat box={box} app={app} />}{tab === 'Sprint' && <StudioSprint box={box} app={app} />}{tab === 'Calls' && <StudioCalls box={box} app={app} />}</div>
    {profile && <Modal onClose={() => setProfile(null)}><div className="profile-sheet"><Avatar user={profile} size="lg" /><span className="eyebrow">THE HUMAN BEHIND THE ROLE</span><h2>{profile.name}</h2><LevelBadge level={profile.level} /><p className="muted">{profile.bio}</p><div className="tag-row">{profile.skills.map(s => <span key={s}>{s}</span>)}</div><div className="profile-stats"><b>{profile.reputation}<small>reputation</small></b><b>{profile.hoursPerWeek}<small>hours / week</small></b><b>{profile.role}<small>crew role</small></b></div><p className="profile-timezone">{profile.timezone} · ready to make something real</p></div></Modal>}
  </Shell>;
}

function StudioChat({ box, app }: { box: Box; app: AppState }) {
  const [text, setText] = useState(''); const [stream, setStream] = useState(''); const [aiBusy, setAiBusy] = useState(false); const [typing, setTyping] = useState(false);
  const scroll = useRef<HTMLDivElement>(null); const timers = useRef<ReturnType<typeof setTimeout>[]>([]); const alive = useRef(true);
  useEffect(() => { alive.current = true; return () => { alive.current = false; timers.current.forEach(clearTimeout); }; }, []);
  useEffect(() => { const node = scroll.current; if (node) node.scrollTop = node.scrollHeight; }, [box.messages.length, typing, stream]);
  const send = () => {
    const message = text.trim(); if (!message) return;
    app.addMessage(box.id, message, app.currentUser!.id); setText(''); setTyping(true);
    timers.current.push(setTimeout(() => { if (!alive.current) return; const teammate = box.slots.find(s => s.filledBy && s.filledBy !== app.currentUser!.id)?.filledBy || 'sam'; app.addMessage(box.id, /ship|build|task/i.test(message) ? 'Yes! Let’s protect the smallest useful version. I can review it in my next focus block.' : 'Glad you’re here. Bring that perspective to the idea vote — I think it could sharpen our direction.', teammate); setTyping(false); }, 1300));
  };
  const generate = async (mode: 'icebreaker' | 'dailyDigest') => {
    if (aiBusy) return;
    setAiBusy(true); setStream(''); let final = '';
    for await (const token of mockAI[mode](box)) { if (!alive.current) return; final = token; setStream(token); }
    if (!alive.current) return;
    app.addMessage(box.id, final, 'AI'); setStream(''); setAiBusy(false);
  };
  return <div className="conversation-layout"><section className="conversation"><div className="conversation-top"><div><MessageCircle size={17} /><span>The crew room</span><small>{box.slots.filter(s => s.filledBy).length} people, one thread</small></div><span className="conversation-live"><i />Open for good ideas</span></div><div className="conversation-messages" ref={scroll} role="log" aria-label="Crew conversation"><div className="chat-date">TODAY / A GOOD DAY TO BUILD</div>{box.messages.map(m => { const u = app.users.find(u => u.id === m.from); const mine = m.from === app.currentUser?.id; return <div className={`studio-message ${mine ? 'mine' : ''} ${m.from === 'AI' ? 'ai' : ''}`} key={m.id}>{u && !mine && <Avatar user={u} size="sm" />}<div><div className="studio-message-meta"><b>{m.from === 'AI' ? 'Local copilot' : mine ? 'You' : u?.name || 'Crew'}</b><time>{m.time}</time></div>{m.from === 'AI' && <OnDeviceBadge />}<p>{m.text}</p></div></div>; })}{stream && <div className="studio-message ai"><div><OnDeviceBadge /><p>{stream}<span className="stream-cursor" /></p></div></div>}{typing && <div className="crew-typing"><i /><i /><i /><span>A crewmate is finding the words…</span></div>}</div><form className="conversation-compose" onSubmit={e => { e.preventDefault(); send(); }}><input aria-label="Message your crew" placeholder="An idea, a question, a little hello…" value={text} onChange={e => setText(e.target.value)} /><button type="submit" aria-label="Send message" disabled={!text.trim()}><ArrowUpRight size={22} /></button></form></section><aside className="conversation-aside"><span className="eyebrow">A LITTLE HELP, WHEN YOU NEED IT</span><div className="copilot-symbol">✳</div><h3>Less awkward.<br />More forward.</h3><p>A tiny prompt can turn a quiet room into the start of something.</p><OnDeviceBadge /><Button disabled={aiBusy} onClick={() => generate('icebreaker')}>AI icebreaker <Sparkles size={15} /></Button><Button disabled={aiBusy} variant="ghost" onClick={() => generate('dailyDigest')}>Daily digest <ArrowUpRight size={15} /></Button><div className="conversation-tip"><ShieldCheck size={17} /><p>Your conversation stays on this device. This is a local demo, not a public chat.</p></div></aside></div>;
}

function StudioSprint({ box, app }: { box: Box; app: AppState }) {
  const [plan, setPlan] = useState<{ day: string; items: string[] }[]>([]); const [doing, setDoing] = useState<string[]>([]); const [vote, setVote] = useState<string | null>(null);
  const reduced = useReducedMotion();
  useEffect(() => { let active = true; mockAI.draftSprintPlan(box).then(p => { if (active) setPlan(p); }); return () => { active = false; }; }, [box.id]);
  const phases = ['Align', 'Prototype', 'Ship', 'Reflect'];
  const columns = [{ title: 'To do', note: 'GOOD INTENTIONS', tasks: box.tasks.filter(t => !t.done && !doing.includes(t.id)) }, { title: 'Doing', note: 'IN MOTION', tasks: box.tasks.filter(t => !t.done && doing.includes(t.id)) }, { title: 'Done', note: 'SMALL WINS', tasks: box.tasks.filter(t => t.done) }];
  const move = (id: string, done: boolean) => { if (done) { app.toggleTask(box.id, id); setDoing(d => d.filter(x => x !== id)); } else if (doing.includes(id)) { app.toggleTask(box.id, id); setDoing(d => d.filter(x => x !== id)); } else setDoing(d => [...d, id]); };
  return <><div className="sprint-roadmap"><div className="roadmap-title"><div><span className="eyebrow">A FOURTEEN-DAY BET ON EACH OTHER</span><h2>Small scope.<br /><span>Real momentum.</span></h2></div><div><OnDeviceBadge /><span>AI-drafted. Human-owned.</span></div></div><div className="roadmap-phases">{(plan.length ? plan : phases.map((_, i) => ({ day: ['Days 1–3', 'Days 4–7', 'Days 8–11', 'Days 12–14'][i], items: ['Drafting your local plan…'] }))).map((p, i) => <div key={p.day}><span className="phase-number">0{i + 1}</span><span className="eyebrow">{p.day}</span><h3>{phases[i]}</h3><p>{p.items.join(' · ')}</p></div>)}</div><div className="sprint-days">{Array.from({ length: 14 }, (_, i) => <span key={i} className={i + 1 === box.sprintDay ? 'current' : i + 1 < box.sprintDay ? 'past' : ''}>{i + 1 < box.sprintDay ? <Check size={12} /> : i + 1}</span>)}</div></div><SectionHeading eyebrow="MAKE IT REAL, ONE TASK AT A TIME" title="The mission board" action={<span className="board-hint">Tap a task to move it forward <ArrowUpRight size={13} /></span>} /><div className="kanban-board">{columns.map((col, i) => <section key={col.title}><div className="kanban-heading"><span>{col.title}<small>{col.tasks.length}</small></span><i className={`kanban-dot dot-${i}`} /></div><span className="eyebrow">{col.note}</span><div className="kanban-tasks"><AnimatePresence>{col.tasks.map(t => { const owner = app.users.find(u => u.id === t.owner); return <motion.button layout={!reduced} initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }} transition={{ duration: .2 }} key={t.id} className={`kanban-task ${t.done ? 'complete' : ''}`} onClick={() => move(t.id, t.done)}><span className="task-coordinate">SB / {t.id.toUpperCase()}</span><h4>{t.title}</h4><div>{owner && <Avatar user={owner} size="sm" />}<span>Day {t.dueDay}</span>{t.done ? <Check size={16} /> : <ArrowUpRight size={16} />}</div></motion.button>; })}</AnimatePresence>{!col.tasks.length && <div className="kanban-empty">{i === 1 ? 'Good work starts with one small move.' : i === 2 ? 'Your first small win goes here.' : 'Clear runway. Nice work.'}</div>}</div></section>)}</div><SectionHeading eyebrow="ONE CLEAR DECISION UNBLOCKS EVERYONE" title="What should we build?" action={<span className="board-hint">The idea vote</span>} /><div className="studio-ideas">{box.ideas.map((idea, i) => <button className={vote === idea.id ? 'voted' : ''} key={idea.id} disabled={vote !== null} onClick={() => { setVote(idea.id); app.vote(box.id, idea.id); }}><span className="eyebrow">BET / 0{i + 1}</span><h3>{idea.title}</h3><div className="idea-meter"><i style={{ width: `${Math.min(100, idea.votes / box.ideas.reduce((a, b) => a + b.votes, 0) * 100)}%` }} /></div><span className="idea-vote-bottom">{idea.votes} crew votes <span>{vote === idea.id ? <><Check size={13} /> Your vote</> : 'Back this idea ↗'}</span></span></button>)}</div></>;
}

function StudioCalls({ box, app }: { box: Box; app: AppState }) {
  const [calling, setCalling] = useState(false); const [muted, setMuted] = useState(false); const [speaker, setSpeaker] = useState(true); const [seconds, setSeconds] = useState(0);
  useEffect(() => { if (!calling) return; const timer = setInterval(() => setSeconds(s => s + 1), 1000); return () => clearInterval(timer); }, [calling]);
  const crew = box.slots.map(s => app.users.find(u => u.id === s.filledBy)).filter(u => u !== undefined);
  if (!calling) return <div className="calls-lobby"><div><span className="eyebrow">A ROOM FOR THE REAL TALK</span><h2>Some things<br />are better <span>said.</span></h2><p>Find a little clarity, share a wild idea,<br />or just put a voice to the initials.</p><Button onClick={() => { setCalling(true); setSeconds(0); }}>Start voice call <Headphones size={17} /></Button><small><ShieldCheck size={13} /> Simulated room. No real audio or microphone access.</small></div><OrbitArt variant="coral" /></div>;
  return <div className="studio-call"><div className="call-top"><span><i />A shared little space</span><time>{`${Math.floor(seconds / 60)}`.padStart(2, '0')}:{`${seconds % 60}`.padStart(2, '0')}</time></div><div className="call-grid">{crew.map((u, i) => <div className="call-person" key={u.id}><div className={i === 0 ? 'speaking' : ''}><Avatar user={u} size="lg" /></div><b>{u.name.split(' ')[0]}</b><small>{u.id === app.currentUser?.id && muted ? 'You · muted' : u.role}</small></div>)}</div><div className="studio-call-controls"><button className={muted ? 'control-off' : ''} aria-label={muted ? 'Unmute microphone' : 'Mute microphone'} aria-pressed={muted} onClick={() => setMuted(!muted)}>{muted ? <MicOff size={20} /> : <Mic size={20} />}</button><Button variant="danger" onClick={() => setCalling(false)}>Leave the room <X size={17} /></Button><button aria-label={speaker ? 'Mute speaker' : 'Enable speaker'} aria-pressed={speaker} onClick={() => setSpeaker(!speaker)}>{speaker ? <Volume2 size={20} /> : <VolumeX size={20} />}</button></div><p className="call-disclaimer">JUST A DEMO / NO AUDIO IS CAPTURED</p></div>;
}
