import { useEffect, useState } from 'react';
import { motion } from 'framer-motion';
import { ArrowRight, ArrowUpRight, Check, ChevronRight, Compass, Flame, Hexagon, LockKeyhole, Search, ShieldCheck, Sparkles, Target, Users, Zap } from 'lucide-react';
import { Link, useNavigate } from 'react-router-dom';
import { Avatar, BoxCard, Brand, Button, Card, Chip, EmptyState, LevelBadge, Modal, OnDeviceBadge, OrbitArt, SectionHeading, Shell, SlotTile, StarfieldBackground, XPBar } from '../components';
import { useApp } from '../store/useApp';
import { DEMO_ACCOUNTS } from '../data/accounts';
import { mockAI } from '../ai/mockAI';
import { Box } from '../types';

export function StudioLogin() {
  const nav = useNavigate(); const app = useApp();
  const [email, setEmail] = useState(''); const [password, setPassword] = useState(''); const [error, setError] = useState('');
  const authenticate = (email: string, password: string) => {
    const account = DEMO_ACCOUNTS.find(a => a.email === email && a.password === password);
    if (!account) { setError('A little turbulence. Use one of the demo accounts below to get started.'); return; }
    const user = app.users.find(u => u.name === account.name)!;
    app.login(user); nav(app.onboardingComplete ? '/home' : '/onboarding');
  };
  return <div className="studio-login"><StarfieldBackground dense />
    <section className="login-story"><Brand /><div className="story-copy"><span className="eyebrow">INDEPENDENT MINDS. SHARED AMBITION.</span><h1>Big ideas.<br />Better <span>people.</span></h1><p>You don't need another idea.<br />You need people who will build it with you.</p></div><div className="login-sculpture"><OrbitArt /><span className="art-caption">FIVE DISTINCT ORBITS.<br />ONE SHARED DIRECTION.</span><div className="sculpture-sticker">find your<br /><b>people ↗</b></div></div><div className="story-foot"><span>01 — FIND YOUR CREW</span><span>02 — BUILD SOMETHING REAL</span><span>03 — KEEP GOING</span></div></section>
    <section className="login-panel"><div className="login-panel-top"><span>YOUR NEXT CHAPTER STARTS HERE</span><Hexagon size={19} /></div><div className="login-panel-content"><span className="eyebrow">WELCOME ABOARD</span><h2>Let's find<br />your kind of crew.</h2><p className="muted">Show up as you are. Leave with a team.</p><form className="auth-form" onSubmit={e => { e.preventDefault(); authenticate(email, password); }}><label>Email address<input autoComplete="username" value={email} onChange={e => { setEmail(e.target.value); setError(''); }} placeholder="you@startupbox.app" type="email" required /></label><label>Password<input autoComplete="current-password" value={password} onChange={e => setPassword(e.target.value)} placeholder="Your demo password" type="password" required /></label>{error && <div role="alert" className="error-msg">{error}</div>}<Button type="submit" className="full">Find my crew <ArrowUpRight size={18} /></Button></form><div className="demo-accounts"><div className="demo-heading"><span>Just exploring?</span><span>Take a demo flight</span></div>{DEMO_ACCOUNTS.map(a => <button key={a.email} onClick={() => { setEmail(a.email); setPassword(a.password); authenticate(a.email, a.password); }}><Avatar user={{ name: a.name, role: a.role, avatarColor: '' }} /><span><b>{a.name}</b><small>{a.role} · {a.email}</small></span><span className="demo-cta">Use demo account <ArrowUpRight size={14} /></span></button>)}</div><div className="login-privacy"><ShieldCheck size={20} /><span><b>Private by design. Personal by nature.</b><small>Your profile and AI processing stay on this device.</small></span></div></div><div className="login-panel-bottom"><span>A PROTOTYPE FOR REAL CONNECTIONS.</span><span>SB / 001</span></div></section>
  </div>;
}

export function StudioHome() {
  const app = useApp(); const user = app.currentUser!;
  const box = app.boxes.find(b => b.id === app.currentBoxId) || app.boxes[0];
  const [digest, setDigest] = useState('');
  const [digestBusy, setDigestBusy] = useState(false);
  const readDigest = async () => { setDigestBusy(true); for await (const text of mockAI.dailyDigest(box)) setDigest(text); setDigestBusy(false); };
  const crew = box.slots.map(s => app.users.find(u => u.id === s.filledBy)).filter(u => u !== undefined);
  const open = app.boxes.filter(b => b.status === 'Open' && b.id !== box.id).slice(0, 3);
  const messagesDone = box.messages.some(m => m.from === user.id);
  const tasksDone = box.tasks.filter(t => t.done).length > 1;
  return <Shell><div className="dashboard-heading"><div><span className="eyebrow">A LITTLE AMBITION GOES A LONG WAY</span><h1>Your next big thing<br />starts <span>with a hello.</span></h1><p className="muted">Welcome back, {user.name.split(' ')[0]}. Your crew is making moves.</p></div><div className="today-label"><span className="live-dot" /> YOUR MISSION IS LIVE<small>Day {box.sprintDay} of 14 <ArrowUpRight size={15} /></small></div></div>
    <div className="dashboard-grid"><section className="featured-mission"><div className="mission-meta"><span><Hexagon size={16} /> CURRENT MISSION</span><span>SB / {box.id}</span></div><div className="featured-copy"><LevelBadge level={box.level} /><h2>{box.name}<span>Small team.<br />Big possibility.</span></h2><p>{box.idea}</p><Link to={`/box/${box.id}`} className="btn btn-primary">Meet your crew <ArrowUpRight size={18} /></Link></div><div className="featured-art"><OrbitArt /><span className="art-label">CONNECTED BY COMMITMENT</span></div><div className="featured-foot"><div className="crew-stack">{crew.slice(0, 4).map(u => <Avatar key={u.id} user={u} size="sm" />)}<span>{crew.length} minds, one mission</span></div><span className="momentum"><i />{box.health}% team momentum</span></div></section>
    <aside className="flight-log"><div className="flight-log-top"><span className="eyebrow">YOUR FLIGHT LOG</span><ArrowUpRight size={17} /></div><div className="flight-log-user"><Avatar user={user} /><div><b>{user.name}</b><span>{user.xp >= 500 ? 'Commander' : 'Navigator'} · {user.level}</span></div></div><XPBar user={user} /><div className="log-metrics"><div><Flame size={19} /><strong>{user.streak}<small>days</small></strong><span>On a streak</span></div><div><Target size={19} /><strong>{user.reputation}<small>/100</small></strong><span>Reputation</span></div></div><div className="log-note"><span>✳</span><p>Consistency is your<br />best superpower.</p></div></aside>
    <section className="crew-pulse"><div className="pulse-heading"><span className="eyebrow">THE CREW PULSE</span><span><i />{crew.length} in orbit</span></div><div className="pulse-people">{crew.slice(0, 4).map((u, i) => <Link key={u.id} to={`/box/${box.id}`}><Avatar user={u} /><span><b>{u.name.split(' ')[0]}</b><small>{u.role}</small></span><i className={`pulse-bar pulse-bar-${i}`} /></Link>)}</div><div className="pulse-bottom"><span>Different strengths. Shared momentum.</span><Link to={`/box/${box.id}`}>Room's open <ArrowRight size={14} /></Link></div></section>
    <section className="daily-signal"><div className="signal-head"><span className="signal-glyph">✳</span><OnDeviceBadge /></div><h3>A nudge,<br />not another notification.</h3><p>{digest || 'One clear decision will unblock the whole crew. Start with the idea vote, then give someone a little momentum.'}</p><button disabled={digestBusy} onClick={readDigest}>{digestBusy ? 'Reading the room…' : 'Read today’s signal'} <ArrowUpRight size={17} /></button></section></div>
    <SectionHeading eyebrow="THERE'S MORE THAN ONE WAY TO BUILD" title="A few other good orbits." action={<Link to="/explore">Explore all boxes <ArrowUpRight size={15} /></Link>} /><div className="home-box-grid">{open.map(b => <BoxCard key={b.id} box={b} users={app.users} />)}</div>
    <div className="quest-strip"><div><span className="eyebrow">SMALL WINS CLUB</span><h3>Make a little progress.</h3></div>{[{ done: messagesDone, title: 'Say hello to the crew', xp: 15, to: `/box/${box.id}` }, { done: tasksDone, title: 'Ship one small task', xp: 25, to: `/box/${box.id}` }, { done: box.status === 'Completed', title: 'Give thoughtful feedback', xp: 100, to: `/sprint/${box.id}/end` }].map(q => <Link key={q.title} to={q.to}><span className={`quest-check ${q.done ? 'complete' : ''}`}>{q.done ? <Check size={15} /> : <ArrowUpRight size={15} />}</span><span><b>{q.title}</b><small>{q.done ? 'Mission accomplished' : `+${q.xp} XP for showing up`}</small></span></Link>)}</div>
  </Shell>;
}

export function StudioExplore() {
  const app = useApp(); const nav = useNavigate();
  const [type, setType] = useState('All'); const [level, setLevel] = useState('All levels'); const [search, setSearch] = useState('');
  const [selected, setSelected] = useState<Box | null>(null); const [joining, setJoining] = useState(false); const [accepted, setAccepted] = useState(false);
  useEffect(() => { setAccepted(false); setJoining(false); }, [selected?.id]);
  const list = app.boxes.filter(b => b.status !== 'Completed' && (type === 'All' || b.type === type) && (level === 'All levels' || b.level === level) && `${b.name} ${b.idea} ${b.type}`.toLowerCase().includes(search.toLowerCase()));
  const locked = selected?.level === 'Founder' && app.currentUser?.level !== 'Founder';
  return <Shell title="Discover boxes"><div className="discover-hero"><div><span className="eyebrow">THE PEOPLE ARE THE POSSIBILITY</span><h1>Find your<br /><span>kind of ambitious.</span></h1><p>Side projects. Big bets. Beautiful experiments.<br />There's a crew out there for your next chapter.</p></div><div className="discover-art"><OrbitArt variant="lavender" /><span className="discover-sticker">a place<br />for your<br /><b>perspective.</b></span></div><span className="hero-coordinate">OPEN ORBITS / VOL. 01</span></div>
    <div className="discovery-tools"><div className="discovery-types">{['All', 'Startup', 'Hackathon', 'Agency', 'Content', 'Research'].map(f => <Chip key={f} active={type === f} onClick={() => setType(f)}>{f === 'All' ? 'All orbits' : f}</Chip>)}</div><div className="discovery-search"><label><Search size={17} /><input aria-label="Search boxes" value={search} onChange={e => setSearch(e.target.value)} placeholder="Search a box, idea, or mission" /></label><select aria-label="Filter commitment level" value={level} onChange={e => setLevel(e.target.value)}><option>All levels</option><option>Explorer</option><option>Builder</option><option>Founder</option></select></div></div><div className="discovery-count"><span>{list.length} places to make something happen</span><span>CURATED BY LOCAL CHEMISTRY <Sparkles size={13} /></span></div>
    <div className="discovery-grid">{list.map(b => <BoxCard key={b.id} box={b} users={app.users} onClick={() => setSelected(b)} />)}</div>{!list.length && <EmptyState icon={<Compass size={32} />} title="A quieter orbit." body="Try another skill, mission, or commitment level."><Button variant="ghost" onClick={() => { setType('All'); setLevel('All levels'); setSearch(''); }}>Clear filters</Button></EmptyState>}
    {selected && <Modal onClose={() => setSelected(null)}><div className="preview-art"><OrbitArt variant="lavender" /><span>SB / {selected.id}</span></div><div className="preview-heading"><span className="eyebrow">{selected.type} / {selected.level}</span><h2>{selected.name}</h2><p className="muted">{selected.idea}</p></div><div className="preview-facts"><span><b>{selected.slots.length}</b>Crew size</span><span><b>{selected.health}%</b>Momentum</span><span><b>14 days</b>First sprint</span></div><h3 className="preview-crew-title">Your potential people</h3><div className="slots-row">{selected.slots.map((s, i) => <SlotTile key={i} role={s.role} filledBy={s.filledBy} users={app.users} />)}</div>{locked ? <div className="locked-box"><LockKeyhole size={20} /><span><b>A higher-commitment orbit.</b><small>Finish sprints and give peer ratings to earn your Founder level.</small></span></div> : accepted ? <div className="accepted-state"><p><Check size={18} /> Your request landed. The crew is ready.</p><Button className="full" onClick={() => nav(`/launch/${selected.id}`)}>Launch into this box <ArrowUpRight size={18} /></Button></div> : <Button disabled={joining || selected.status === 'Full' || selected.status === 'Sprinting'} className="full" onClick={() => { setJoining(true); setTimeout(() => { app.joinBox(selected.id); setJoining(false); setAccepted(true); }, 1800); }}>{joining ? 'Checking your orbit…' : selected.status !== 'Open' ? 'This crew is already underway' : 'Request a seat'} {!joining && <ArrowUpRight size={18} />}</Button>}<p className="preview-note"><ShieldCheck size={12} /> No pressure. Start with a trial sprint.</p></Modal>}
  </Shell>;
}
